# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 07:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0060_speakinglesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listeningtopic',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='main_form',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
