# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0062_usertest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='finish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
