# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0064_useranswer_usertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
