# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0065_usertest_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
